Repository AOSSIE-Org/Resonate-Backend, pull requests merged in 2023-08, with the labels that each got.

#29 Appwrite functions implemented
  .gitignore
  README.md
  appwrite_cloud_functions/.DS_Store
  appwrite_cloud_functions/send_otp/functions/send_otp/.gitignore
  appwrite_cloud_functions/send_otp/functions/send_otp/README.md
  appwrite_cloud_functions/send_otp/functions/send_otp/package-lock.json
  appwrite_cloud_functions/send_otp/functions/send_otp/package.json
  appwrite_cloud_functions/send_otp/functions/send_otp/src/send_otp.js
  appwrite_cloud_functions/set_email_verified/functions/set_verified/.gitignore
  appwrite_cloud_functions/set_email_verified/functions/set_verified/README.md
  appwrite_cloud_functions/set_email_verified/functions/set_verified/package.json
  appwrite_cloud_functions/set_email_verified/functions/set_verified/src/set_verified.js
  appwrite_cloud_functions/verify_otp/functions/verify_otp/.gitignore
  appwrite_cloud_functions/verify_otp/functions/verify_otp/README.md
  appwrite_cloud_functions/verify_otp/functions/verify_otp/package.json
  appwrite_cloud_functions/verify_otp/functions/verify_otp/src/verify_otp.js
  constants/constants.js
Labels: enhancement

#34 Appwrite Token Validation before serving API
  app.js
  controllers/createRoom.js
  controllers/deleteRoom.js
  controllers/joinRoom.js
  controllers/verifyAppwriteToken.js
Labels: enhancement, gsoc

#37 Implemented Matchmaking Appwrite Cloud Function for Pair-Chat Feature
  appwrite_cloud_functions/functions/match_maker/.gitignore
  appwrite_cloud_functions/functions/match_maker/README.md
  appwrite_cloud_functions/functions/match_maker/package.json
  appwrite_cloud_functions/functions/match_maker/src/index.js
  appwrite_cloud_functions/send_otp/functions/send_otp/src/index.js
  appwrite_cloud_functions/set_email_verified/functions/set_verified/src/index.js
  appwrite_cloud_functions/verify_otp/functions/verify_otp/src/index.js
Labels: enhancement, gsoc

#40 Deployed Resonate Express API to Vercel
  README.md
  appwrite_cloud_functions/functions/match_maker/src/index.js
  index.js
  package.json
  vercel.json
Labels: gsoc
